config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/about' => 'static_pages#about'
  get '/u' => 'static_pages#u'
  get '/blm' => 'static_pages#BLM'
  get '/BLM' => 'static_pages#BLM'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  get '/313tree' => 'static_pages#313tree'
  get '/313Tree' => 'static_pages#313tree'
  get '/treeteam' => 'static_pages#treeteam'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  delete 'destroy_account' => 'users#destroy'
  
  resources :users
  resources :things
  resources :trees

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/thing.rb
class Thing < ApplicationRecord
  # Associations

  belongs_to :creator, class_name: 'User'

  ###################################

  validates :title, presence: true
  validates :description, presence: true, length: {maximum: 255}
  validates :location, presence: true, length: {maximum: 30}
  validates :price, presence: true

  default_scope -> {order('title asc')}

  end

app/models/tree.rb
class Tree < ApplicationRecord
   default_scope -> {order('zip_code asc','street_name asc','adress asc')}
end

app/models/user.rb
class User < ApplicationRecord

  # Associations

  has_many :created_things, class_name: 'Thing', foreign_key: :creator_id, :dependent => :destroy
 
###########################################################

  before_save {self.email.downcase!}
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, :format => {with: VALID_EMAIL_REGEX}, length: {maximum: 255}, uniqueness: true, if: :email_changed?
  validates :password, presence: true, length: {minimum: 8}, allow_blank: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_user
    redirect_to root_url and flash[:danger] = "You are not logged in" if !logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :login_filter, only: [:new, :create]
  before_action :logout_filter, only: :destroy

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "Successfully logged in"
      redirect_to root_url
    else
      flash.now[:danger] = "Incorrect credentials"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  private

  def login_filter
    redirect_to root_url and flash[:danger] = "You are already logged in" if logged_in?
  end

  def logout_filter
    redirect_to root_url and flash[:danger] = "Cannot access logout action when you are not logged in" if !logged_in?
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  @things = Thing.all
  end

  def about
  end
    
  def u
  end

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @thing = Thing.new
  end

  def create
    @thing = current_user.created_things.build(thing_params)
    if @thing.save
      flash[:success] = "You have added a new Thing!"
      redirect_to @thing #things_path later
    else
      flash[:danger] = "The form contains errors"
      render :new
    end
  end

  def index
  @things = Thing.all
  end

  def show
  @thing = Thing.find(params[:id])
  end

  def edit
  @thing = Thing.find(params[:id])
  end

  def update
    @thing.update_attributes(thing_params)
    if @thing.save
      flash[:success] = "Update successful"
      redirect_to @thing
    else
      flash[:danger] = "Something went wrong"
      render :edit
    end
  end

  def destroy
    if @thing.destroy
      flash[:success] = "Your Thing was deleted successfully"
      redirect_to root_url
    else
      flash[:danger] = "Could not delete"
      render @thing
    end
  end

  private

  def thing_params
    params.require(:thing).permit(:title, :description, :location, :price)
  end

  def correct_user
  @thing = Thing.find(params[:id])
    if current_user != @thing.creator
      flash[:danger] = "You don't have permission to do that."
      redirect_to root_url
    end
  end

 end

app/controllers/trees_controller.rb
class TreesController < ApplicationController

  def new
    @tree = Tree.new
  end

 def create
    @tree = Tree.new(tree_params)
    if @tree.save
      flash[:success] = "You have added a new tree request!"
      redirect_to @tree #trees_path later
    else
      flash[:danger] = "The form contains errors"
      render :new
    end
  end

  def index
  @trees = Tree.all
  end

  def show
  @tree = Tree.find(params[:id])
  end

  def edit
  @tree = Tree.find(params[:id])
  end

  def update
  	@tree = Tree.find(params[:id])  
  	@tree.update_attributes(tree_params)
    if @tree.save
      flash[:success] = "Update successful"
      redirect_to :treeteam 
    else
      flash[:danger] = "Something went wrong"
      render :edit
    end
  end

  def destroy
  	@tree = Tree.find(params[:id])   
    if @tree.destroy
      flash[:success] = "Your Tree was deleted successfully"
      redirect_to :treeteam
    else
      flash[:danger] = "Could not delete"
      render @tree
    end
  end

  private

  def tree_params
    params.require(:tree).permit(:owner_name, :adress, :street_name, :zip_code, :owner_phone, :message, :current_estimate, :company_name, :company_contact, :company_phone)
  end
  
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :edit_own_profile, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Registered successfully"
      redirect_to root_url
    else
      flash.now[:danger] = "Form contains errors"
      render :new
    end
  end


  def edit
  @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    if @user.save
      flash[:success] = "Profile updated"
      redirect_to root_url
    else
      flash.now[:danger] = "Something went wrong"
      render :edit
    end
  end

  def destroy
    if current_user.destroy
      log_out
      flash[:success] = "Account deleted."
      redirect_to root_url
    else
      flash[:danger] = "Something went wrong"
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
	@created_things = @user.created_things
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def edit_own_profile
    redirect_to root_url and flash[:danger] = "Access denied" if current_user.id.to_s != params[:id].to_s
  end

  def create_user_instance
    @user = User.find(params[:id])
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(title)
    default_title = "The F & P"
    if title.empty?
      default_title
    else
      title + " | " + default_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/things_helper.rb
module ThingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
	            <small> <%= Time.now %> </small>
		  <br><small> XOtoZ </small><br> 
<small> beta 1.1 </small>
        </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
  <div class="container topnav">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation_menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_url, id: 'logo', class:'navbar-brand topnav custom-hover' do %>
          
         The F & P { <%= Thing.count %> } <small> beta 1.1 </small>
		 
      <% end %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navigation_menu">
      <ul class="nav navbar-nav navbar-right">
	  
		

        <% if logged_in? %>
            <li class="custom-hover">
              <%= link_to new_thing_path do %>
                  Make-a-Thing
              <% end %>
            </li>

        <% end %>

        <li class="custom-hover">
          <%= link_to about_path do %>
              About
          <% end %>
        </li>

        <% if !logged_in? %>
            <li>
              <%= link_to login_path do %>
                  Log In
              <% end %>
            </li>

        <% else %>

            <li class="dropdown custom-hover">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                menu:{<%= current_user.name %>}</b>
              </a>
              <ul class="dropdown-menu" style="width: 230px;border-radius:10px;">
                <li style="padding-left:10px;">Hello, <%= current_user.name %>!</li>
                <li class="divider"></li>
                <li><%= link_to current_user do %>
                      Your Things 
                  <% end %>
                </li>
                <li><%= link_to edit_user_path(current_user) do %>
                     Your Profile
                  <% end %>
                  <li class="divider"></li>
                  <li>
                    <%= link_to logout_path, method: "delete" do %>
                      Log Out
                    <% end %>
                  </li>
                  </ul>
            </li>

        <% end %>


      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<link href='https://fonts.googleapis.com/css?family=Bangers|Special+Elite|Permanent+Marker|Cutive+Mono|Amatic+SC|Sancreek' rel='stylesheet' type='text/css'>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<div class="container-fluid" id="wrap">
<div class="row">

</div> 
  <%= yield %>
</div>



<%= render 'layouts/footer' %>

<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="error_explanation">
      <div class="alert alert-danger alert-dismissible text-center">
        The form contains <%= pluralize(object.errors.count, "error") %>
      </div>

      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li style="color:red;"><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<div class="col-md-6 col-md-offset-3" style="margin-top:10px;">
    <% flash.each do |type, msg| %>
        <%= content_tag :div, class: "alert alert-#{type} alert-dismissable text-center" do %>
            <%= msg %>
            <button type="button" class="close" data-dismiss="alert"
                    aria-hidden="true">
              &times;
            </button>
        <% end %>
    <% end %>

  </div>

app/views/static_pages/313tree.html.erb
<h1>#313treeproject</h1>
<p>Creating an economy for urgent and affordable tree work to stabilize communities by protecting Detroit homeowners from life threatening foliage.</p>
<hr>
<h6>Do you know of a tree that needs serviced?</h6>
<p>Please click the SERVICE REQUEST link below.</p>
 <a href="/trees/new">
                  SERVICE REQUEST
</a>
<hr>
<h1>TOTAL REQUESTS: <%= Tree.count %></h1>
<p1>
<% @trees = Tree.all() %>
<% @trees.each do |tree| %> 
<%= tree.adress %> <%= tree.street_name %>, <%= tree.zip_code %> <br>
<% end %>
</p1>

<hr>
<small>Need support? <a href="mailto:ter.reub@gmail.com">ter.reub@gmail.com</a></small>
<hr>

<h6>ABOUT</h6>

<p>The #313treeproject goals are to
<br>
1) locate & record the location of dangerous trees and limbs for city officials, neighborhood organizations, arborists and philanthropists
<br>
2) organize strategic actions so that resources, personpower and logistics can be efficiently managed
<br>
3) attract philanthropic contributions for low cost and free removal for those in need.
<br>
4) safely and efficiently trim or remove these trees by winter each year until all dangerous trees are handled.
<br>
5) utilize the remnants of these trees for compost, firewood, furniture and construction materials to support neighborhood sustainability while lowering the cost of future services.
<hr>

app/views/static_pages/313treeteam.html.erb
<h1>#313treeproject</h1>
<h1>TEAM VIEW</h1>
<hr>
<small>Need technical support or have a question? Call 313-740-7798 or email <a href="mailto:ter.reub@gmail.com">ter.reub@gmail.com</a></small> .
<hr>
<h4>Tree</h4> <%= link_to 'NEW TREE', new_tree_path %>
<table class="center" cellpadding="10">
    <tr align="center">
		<th></th>
    	<th>Name</th>
        <th>Adress</th>
        <th>Zip</th>
        <th>#</th>
        <th align="center">ID</th>
        <th></th>
	<th></th>
    </tr>

  <% @trees = Tree.all() %>
  <% @trees.each do |tree| %>
   <tr align="left">
	  <td></td>
      <td><p><%= tree.owner_name %></p> </td>
	  <td><p><%= tree.adress %></p> </td>
	  <td><p><%= tree.zip_code %></p> </td>
	  <td><p><%= tree.owner_phone %></p> </td>
	  <td align="center"><p><%= tree.id %></p> </td>
      <td><%= link_to 'Edit', edit_tree_path(tree) %></td>
	  <td><%= link_to 'Destroy', tree_path(tree),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/static_pages/BLM.html.erb
<h1>#BLMfinance NETWORK</h1>
<h6>a job for Bitcoin</h6>
<hr>
<p><i>"I believe #blacklivesmatter movement is being exploited to justify marshall law."</i></p> 
<hr>
<p>Since 2009, a financial technology of the internet has been ignored, suppressed and attacked.</p>

<h5>Sound familiar?</h5>

<p>This technology has the ability to <u>peacefully</u> uppend national and international monetary scams by global corporations and central banking masters.</p>

<p>Have you heard about <a href="http://hiddensecretsofmoney.com/videos/episode-4"> THE "FEDERAL" RESERVE SCAM </a> ?
</p>
<hr>
<p>Once you understand the system is designed to trap, enslave and fail, WE must ask ourselves why this system STILL exists. The answer is likely routed in survival. We are still well within the Reagon Era where scarcity, shock and awe, policing, and profits claim to make strides for the American individual. For instance, we are forced to debate the amount of minimum wage as opposed to whether or not an hourly wage is a reasonable way to employ. Why not offer hourly employees a percentage of the profit? When you think about it, the amount an hourly wage pays is arbitrary when we are negotiating with corporations who are financed directly by the money printers through FDIC insured banks that lend 10x of what actually exists. Money printing, within a "fractional reserve" system, creates unpayable debts to governments while decreasing the value of the currency for everday Americans.</p> 
<hr>
<p><a href="https://www.youtube.com/watch?v=6lIqNjC1RKU"> Reagon by Killer Mike </a></p>
<hr>
<p>This is happening around the world and is a result of "centralized" (profit based) models for resource distribution cannot keep up with increasing demands upon the system. America will be the last to see the true cost of centralized economies being run by corporations. Why? Because the United States has the strongest military and thereby forces a strong and seemingly silent hand during negotiations. In short, the military complex has many shades of mercinaries willing to police for profits both foreign and domestic.</p>
<hr>
<p><a href="https://www.youtube.com/watch?v=j8d-IYSM-08"> MLK - THREE EVILS OF SOCIETY </a></p>
<hr>

<p>A global financial revolution could be the only chance we have to supress militarized corporations burdened with sustaining a global population inside a profit centric model. As new technologies develop, we have a choice to adopt or ignore them. Despite new levels of efficiency and transparency, If MLK and JFK had Bitcoin, Digital currencies have the ability to peacefully transfer wealth from one global system of centralized financial control to another that is designed to be "un-central" or decentralized. If you are willing to put your life on the line by physically protesting, why not put some of your income toward a financial movement designed to end this struggle?</p>
<hr>
<h2>BITCOIN vs FDIC</h2>
<p>
The "Federal" model of creating(printing $) and distributing wealth(a % of printed $) is throttled by banks through interest rates and overdraft fees. For most people, money originates in a pay check. Once deposited, your wealth becomes a fraction of a bank's holdings.
</p>
<hr>
<p><a href="https://blockchain.info/wallet/#/signup"> GET A BITCOIN WALLET (like an email address) FREE! </a></p>
<hr>
<p><a href="https://www.coinbase.com/"> CONNECT YOUR U$D WITH BITCOIN (like paypal) FREEE! </a></p>
<hr>






<p>What's next?:
<br>

<hr>
<h2>
<a href="http://www.theohyeah.com/bounties/"> #BLMfinance </a>

<b>NOT CREATED YET</b>
<br>

<hr>

<a href="http://www.theohyeah.com/bounties/3"> #freemckee </a>

<b>1PHi6DEG8DHAsxU2xrR8wk7mL7dJJZjRcA</b>

<hr>

<a href="http://www.theohyeah.com/coins/1"> #halfnotes </a>

<b>12WjcuSckG3yrBzGfF9Nk74mRhHAkMriMq</b></h2>
<hr>
<p>Would you like to promote your own Bitcoin bounty?</p>
<br>
<p>We'd like to list it!
<br>
<p>Please email <a href="mailto:whalebone.earth@gmail.com">whalebone.earth@gmail.com</a></p>
<h5>OR</h5>
<p>Build your own listing!!!</p>



app/views/static_pages/about.html.erb
<%= provide(:title, "About") %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h4 class="text-center" style="font-weight: normal">ABOUT</h4>
    <div class="well" id="about-well">
<h20>
"Great things are done by a series of small things brought together."
</h20>
<small> [ Vincent Van Gogh ] </small>   
<h21>
<hr>
The F & P { <%= Thing.count %> } is a listing of goods and services available for barter/trade with decentralized links for U$D/Bitcoin/credit_card checkout. Our listing is designed to inspire local & frontier digital economies with a limit of 500 listings per URL.
<hr>
To join this local Detroit barter network, please call or text Terri at 313-782-3330 for our private listing URL.
</h21>

    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<%= provide(:title, "XOtoZ") %>
<div class="intro-header">
  <div class="container">

    <div class="row">
      <div class="col-lg-12">
        <div class="intro-message">

<h2>Farmers' & Pirates'</h2>
<h5>[Detroit]</h5>
<p>"A swimmmingly good listing of things."
</p>

<table class="center" cellpadding="10">
    <tr align="center">
		<th>thing</th>
        <th>$$$$</th>
		<th>maker</th>
	
	</tr>
	
  <% @things.each do |thing| %>
   <tr align="center">
	  <td><p><%= link_to thing.title, thing_path(thing) %></p> </td>
	  <td><p><%= number_to_currency(thing.price, :unit => "$") %></p> </td>
	  <td><p><%= link_to thing.creator.name, user_path(thing.creator) %></p> </td>
	 
   </tr>
  <% end %>
</table>
           
		  
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/treeteam.html.erb
<h1>#313treeproject</h1>
<h1>TEAM VIEW</h1>
<hr>
<small>Need technical support or have a question? Call 313-740-7798 or email <a href="mailto:ter.reub@gmail.com">ter.reub@gmail.com</a></small> .
<hr>
<h4>Trees in the D</h4> <%= link_to 'NEW TREE', new_tree_path %>
<table class="center" cellpadding="10">
    <tr align="center">
		<th></th>
    	<th>Name</th>
    	<th>House#</th>
        <th>Street Name</th>
        <th>Zip</th>
        <th>#</th>
        <th>Note</th>
        <th align="center">ID</th>
        <th></th>
	<th></th>
    </tr>

  <% @trees = Tree.all() %>
  <% @trees.each do |tree| %>
   <tr align="left">
	  <td></td>
      <td><p><%= tree.owner_name %></p> </td>
	  <td><p><%= tree.adress %> </p> </td>
	  <td><p><%= tree.street_name %></p> </td>
	  <td><p><%= tree.zip_code %></p> </td>
	  <td><p><%= tree.owner_phone %></p> </td>
	  <td><p><%= tree.message %></p> </td>
	  <td align="center"><p><%= tree.id %></p> </td>
      <td><%= link_to 'Edit', edit_tree_path(tree) %></td>
	  <td><%= link_to 'Delete', tree_path(tree),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/static_pages/u.html.erb
<hr class="intro-divider">
          <ul class="list-inline intro-social-buttons">

            <% if !logged_in? %>
                <li>
                  <%= link_to signup_path, class: "btn btn-default btn-lg" do %>
                      <span class="network-name">Sign Up!</span>
                  <% end %>
                </li>
            <% else %>
                <li>
				<p>You are logged in!</p><br>
                  <%= link_to new_thing_path, class: "btn btn-default btn-lg" do %>
                     <span class="network-name">Make-A-Thing</span>
                  <% end %>
                </li>

            <% end %>
          </ul>
<hr>

app/views/things/_thing.html.erb
  <div class="row">
  <div class="col-md-6 col-md-offset-3 col-sm-10 ">
      <% @created_things.each do |thing| %><% end %>
	  <div class="well border-blue" style="background: whitesmoke;">
	  <h20>
	  <%= link_to thing.title, thing_path(thing), class: 'custom-hover2', style: 'text-decoration: none;color:black;' %>
      </h20>
	  <br>
      <h20>
      <%= number_to_currency(thing.price, :unit => "$") %>
      </h20>
      <br>
      <h21>
	  <%= thing.location %> 
	  </h21>
	  <hr>
      <% if current_user == thing.creator %>
          <div class="col-md-4 col-sm-12">
            <%= link_to "Edit", edit_thing_path(thing), class: 'btn btn-block btn-warning' %>
          </div>
          <div class="col-md-4 col-sm-12">
            <%= link_to "Delete", thing, method: :delete, data: {confirm: true}, class: 'btn btn-block btn-danger' %>
     	 
		  </div>
	  <% end %>
      </div>
      
  </div>

</div>

app/views/things/show.html.erb
<% provide(:title, @thing.title) %>

<div class="row" style="margin-top: 20px;">
  <div class="col-md-6 col-md-offset-1">
    <div class="well border-blue" style="background: whitesmoke;">
      <h21><%= @thing.special_offer%></h21>
	  <hr>
	 <small>[beta 1.1] image coming soon!
      <hr>
      <%= link_to @thing.title, thing_path(@thing), class: 'custom-hover2', style: 'text-decoration: none;color:black;' %>
     <br>
      <h20>...</h20>
     <br>
      <h21>
        <%= @thing.description %>
      </h21>
<br>
      <h20>...</h20>
     <br>
      <h21>
      <small>LOCATION</small>
      <%= @thing.location %>
      </h21>
      <small>PRICE U$D</small>
      <h20><%= number_to_currency(@thing.price, :unit => "$") %></h20>
	  <hr>
	  <small>HASHTAGS</small>
	  <h20><%= @thing.hashtag %></h20>
	  <hr>
      	<h20>WEBSITE</h20>
	<br>
    <h21>
    <a href="http://<%= @thing.website %>" target="blank"><%= @thing.website %></a></h21>
      <hr>
<h20>BUY NOW VIA SQUARE:</h20>
<br>
<h21><a href="http://<%= @thing.checkout_cc %>" target="blank"><%= @thing.checkout_cc %></a></h21>
<h2>~</h2>
<h20>BUY NOW VIA BITCOIN:</h20>
<br>
<h21><a href="http://<%= @thing.checkout_btc %>" target="blank"><%= @thing.checkout_btc %></a></h21>
<hr>
<h20> <%= @thing.title %> by: <%= link_to @thing.creator.name, user_path(@thing.creator) %> / <%= @thing.creator.farmer_or_pirate %>
</h20>
    </div>
</div>

app/views/trees/edit.html.erb
<% provide(:title, @tree.adress) %>
<div class="intro-header2">
  <%= render 'trees/form' %>
</div>

app/views/trees/new.html.erb
<div class="intro-header">
<%= render 'trees/form' %>
</div>

app/views/trees/show.html.erb
<% provide(:title, @tree.adress) %>

<div class="row" style="margin-top: 20px;">
  <div class="col-md-6 col-md-offset-1">
    <div class="well border-blue" style="background: whitesmoke;">
<h21> <%= @tree.adress %> <%= @tree.street_name %> </h21>
	<hr>
<h21><%= @tree.zip_code %></h21>
	<hr>
<h20><%= @tree.owner_name %></h20>
     	  <hr>
<h20><%= @tree.owner_phone %></h20>
	  <hr> 
<h20><%= @tree.message %></h20>
	  <hr>
 <h20><%= @tree.current_estimate %></h20>
	  <hr>
 <h20><%= @tree.company_name %></h20>
	  <hr>
 <h20><%= @tree.company_contact %></h20>
	  <hr> 
<h20><%= @tree.company_phone %></h20>
	  <hr>
<h20>Your request has been delivered.</h20><hr>
<%= link_to new_tree_path do %>
          
         Send another request!
		 
<% end %>
<hr>
<a href="http://www.xotoz.com/313tree"> Back to #313treeproject home </a>
    </div>
</div>

app/views/users/edit.html.erb
<div class="intro-header2">
  <%= render 'users/form' %>
</div>

app/views/users/new.html.erb
<div class="intro-header2">
<%= render 'users/form' %>
    </div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<% if @created_things.any? %>
<%= render @created_things %>

<% end %>